# Generated by Django 5.1.2 on 2024-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_teste_equipamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='usuario',
        ),
        migrations.AddField(
            model_name='teste',
            name='equipamentos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='om_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
