# Generated by Django 5.1.2 on 2024-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_teste_descricao_remove_teste_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='descricao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='resultado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='usuario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
